spring.application.name=busanit501-EC2

spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

# 1. URL 변경: 본인의 RDS 엔드포인트 주소로 변경했습니다.
# (주의: 주소 끝에 있는 /webdb 는 접속할 데이터베이스 이름입니다. 본인이 생성한 DB명으로 맞게 수정하세요)
spring.datasource.url=jdbc:mariadb://busanit401-database.c3g40co6m7a5.ap-northeast-2.rds.amazonaws.com/wedb?serverTimezone=Asia/Seoul&useSSL=true

# 2. 계정 정보 변경: 본인의 RDS 아이디와 비밀번호를 입력합니다.
spring.datasource.username=busanit401
spring.datasource.password=1234qwer!!

# //for test (데이터베이스 커넥션 풀 설정 - 유지)
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.maximum-pool-size=2

# JPA 및 하이버네이트 설정 (유지)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true

# 로깅 설정
logging.level.org.springframework=info
# 3. 패키지명 변경: org.zerock 부분을 '본인 프로젝트의 기본 패키지명'으로 꼭 변경해 주세요! (예: com.busanit501.board)
logging.level.com.busanit501=debug
logging.level.org.springframework.security=trace